update

diff --git a/scripts/lab b/scripts/lab
--- a/scripts/lab
+++ b/scripts/lab
@@ -18,7 +18,7 @@ export ANSIBLE_CONFIG=${LAB_MGR_DIR}/ansible.cfg
 
 usage() {
   CMD_NAME=$(basename ${0})
-  echo -e  "\e[31m \n"
+  echo -e  "\e[31m"
   echo -e "Usage-1: $CMD_NAME (deploy|destroy|reconfigure|reset) [ -i instance_name ] [ -p pod_name ]"
   echo -e "Usage-2: $CMD_NAME prep  -c course_name"
   echo -e "\e[0m \n"
@@ -26,10 +26,11 @@ usage() {
 }
 
 count_cmd_args() {
-  if [ ${OPTIND} -lt 2 ];
+  if [ ${#@} -lt 3 ];
     then 
-      echo "No options were passed"
+      echo -e  "\e[31mLess arguments were passed \e[0m "
       usage
+      exit 2
   fi
 }
 
@@ -159,7 +160,12 @@ case ${1} in
     course_exec_prep
     ;;
 
-  help|*) usage;;
+  help|h) usage
+    ;;
+  *)
+    echo -e  "\e[31mInvalid argument\e[0m "
+    usage
+    ;;
 esac
 
 
